import { JobApplication } from '../types/application';

export const SAMPLE_APPLICATIONS: JobApplication[] = [
  {
    id: 'demo_1',
    company: 'Stripe',
    companyDomain: 'stripe.com',
    role: 'Senior Software Engineer - Distributed Systems',
    location: 'San Francisco, CA (Hybrid)',
    salary: '$185,000 - $240,000 / year',
    appliedAt: '2026-09-28',
    status: 'Interview',
    endDate: '2026-10-25',
    vacancies: '3 Openings',
    source: 'LinkedIn',
    jobUrl: 'https://www.linkedin.com/jobs/view/stripe-senior-swe-distributed-systems',
    summary: 'Core engineering role designing high-throughput, low-latency financial infrastructure and distributed storage.\nRequires extensive experience in Go or Java, SQL/NoSQL databases, and large-scale concurrency.',
    skills: ['Go', 'Distributed Systems', 'PostgreSQL', 'High Concurrency', 'Redis'],
    notes: 'Referred by Dave M. Prepare deep-dive on distributed consensus and rate-limiting patterns.',
    timeline: [
      { id: 't1', type: 'Applied', date: '2026-09-28', status: 'Applied' },
      { id: 't2', type: 'Recruiter Screening', date: '2026-10-02', status: 'Screening' },
      { id: 't3', type: 'Technical Screen', date: '2026-10-06', status: 'Interview' },
    ],
    createdAt: '2026-09-28T10:00:00.000Z',
    updatedAt: '2026-10-06T15:30:00.000Z',
  },
  {
    id: 'demo_2',
    company: 'Google',
    companyDomain: 'google.com',
    role: 'Software Engineer III',
    location: 'Bengaluru, India',
    salary: '₹42 - ₹55 LPA',
    appliedAt: '2026-10-01',
    status: 'Assessment',
    endDate: '2026-10-12',
    vacancies: '5 Openings',
    source: 'Google Careers',
    jobUrl: 'https://careers.google.com/jobs/results/123456789',
    summary: 'Backend infrastructure role on Google Cloud networking team focusing on software-defined routing.\nRequires deep C++ or Go expertise, algorithms, distributed systems architecture, and Linux internals.',
    skills: ['C++', 'Go', 'Networking', 'Algorithms', 'Linux'],
    notes: 'Recruiter contacted on LinkedIn. Focus on graph algorithms and memory management.',
    timeline: [
      { id: 't4', type: 'Applied', date: '2026-10-01', status: 'Applied' },
      { id: 't5', type: 'Online Assessment Sent', date: '2026-10-04', status: 'Assessment' },
    ],
    createdAt: '2026-10-01T14:20:00.000Z',
    updatedAt: '2026-10-04T09:15:00.000Z',
  },
  {
    id: 'demo_3',
    company: 'Microsoft',
    companyDomain: 'microsoft.com',
    role: 'Software Development Engineer II',
    location: 'Hyderabad, India',
    salary: '₹34 - ₹42 LPA',
    appliedAt: '2026-09-20',
    status: 'Offer',
    endDate: '2026-10-18',
    vacancies: '2 Openings',
    source: 'LinkedIn',
    jobUrl: 'https://careers.microsoft.com/us/en/job/987654321',
    summary: 'Full-stack software engineering role building Azure developer tooling and cloud observability services.\nRequires TypeScript/C#, cloud architecture, distributed telemetry, and RESTful service design.',
    skills: ['TypeScript', 'C#', '.NET', 'Azure', 'Microservices'],
    notes: 'Received written offer from recruiter Sarah. Negotiating joining bonus and equity tranche.',
    timeline: [
      { id: 't6', type: 'Applied', date: '2026-09-20', status: 'Applied' },
      { id: 't7', type: 'Technical Interview', date: '2026-09-27', status: 'Interview' },
      { id: 't8', type: 'System Design Round', date: '2026-10-01', status: 'Technical Interview' },
      { id: 't9', type: 'HR & Director Chat', date: '2026-10-03', status: 'HR Interview' },
      { id: 't10', type: 'Offer Extended', date: '2026-10-05', status: 'Offer' },
    ],
    createdAt: '2026-09-20T11:00:00.000Z',
    updatedAt: '2026-10-05T18:00:00.000Z',
  },
  {
    id: 'demo_4',
    company: 'Amazon',
    companyDomain: 'amazon.com',
    role: 'Software Development Engineer (SDE I)',
    location: 'Seattle, WA / Remote',
    salary: '$145,000 - $165,000 / year',
    appliedAt: '2026-09-25',
    status: 'Technical Interview',
    endDate: '2026-10-09',
    vacancies: '8 Openings',
    source: 'Amazon Jobs',
    jobUrl: 'https://amazon.jobs/en/jobs/24681357',
    summary: 'Core services developer on AWS DynamoDB team responsible for partition management and durability.\nRequires strong Java or C++, data structures, object-oriented design, and operational excellence.',
    skills: ['Java', 'DynamoDB', 'AWS', 'Object Oriented Design'],
    notes: 'Passed initial screening. Need to review Amazon Leadership Principles with STAR format examples.',
    timeline: [
      { id: 't11', type: 'Applied', date: '2026-09-25', status: 'Applied' },
      { id: 't12', type: 'Online Assessment (OA2)', date: '2026-09-29', status: 'Assessment' },
      { id: 't13', type: 'Interview Invite', date: '2026-10-03', status: 'Technical Interview' },
    ],
    createdAt: '2026-09-25T08:30:00.000Z',
    updatedAt: '2026-10-03T16:45:00.000Z',
  },
  {
    id: 'demo_5',
    company: 'Atlassian',
    companyDomain: 'atlassian.com',
    role: 'Backend Engineer - Jira Cloud',
    location: 'Bengaluru, India (Remote)',
    salary: '₹30 - ₹38 LPA',
    appliedAt: '2026-10-02',
    status: 'Screening',
    endDate: '2026-10-15',
    vacancies: '1 Opening',
    source: 'Wellfound',
    jobUrl: 'https://wellfound.com/jobs/atlassian-backend-engineer',
    summary: 'Backend developer on Jira Cloud core team scaling multi-tenant issue tracking microservices.\nRequires Java/Kotlin, Spring Boot, event-driven architecture with Kafka, and relational databases.',
    skills: ['Java', 'Kotlin', 'Kafka', 'Spring Boot', 'PostgreSQL'],
    notes: 'Applied via Wellfound. Flexible remote policy.',
    timeline: [
      { id: 't14', type: 'Applied', date: '2026-10-02', status: 'Applied' },
      { id: 't15', type: 'Screening Scheduled', date: '2026-10-05', status: 'Screening' },
    ],
    createdAt: '2026-10-02T13:00:00.000Z',
    updatedAt: '2026-10-05T12:00:00.000Z',
  },
  {
    id: 'demo_6',
    company: 'Adobe',
    companyDomain: 'adobe.com',
    role: 'Software Engineer - Creative Cloud',
    location: 'Noida, India',
    salary: '₹24 - ₹30 LPA',
    appliedAt: '2026-09-15',
    status: 'Rejected',
    endDate: '2026-09-30',
    vacancies: '2 Openings',
    source: 'Naukri',
    jobUrl: 'https://www.naukri.com/job-listings-adobe-software-engineer-15092026',
    summary: 'Frontend and graphics engine development for Creative Cloud Web applications.\nRequires modern JavaScript/TypeScript, WebAssembly, WebGL/WebGPU fundamentals, and Canvas rendering.',
    skills: ['TypeScript', 'WebGL', 'WebAssembly', 'React', 'C++'],
    notes: 'Received automated rejection after 3 weeks. Keep in touch with recruiter for future openings.',
    timeline: [
      { id: 't16', type: 'Applied', date: '2026-09-15', status: 'Applied' },
      { id: 't17', type: 'Position Closed', date: '2026-10-04', status: 'Rejected' },
    ],
    createdAt: '2026-09-15T09:00:00.000Z',
    updatedAt: '2026-10-04T10:00:00.000Z',
  },
  {
    id: 'demo_7',
    company: 'Deloitte',
    companyDomain: 'deloitte.com',
    role: 'Applied AI Site Reliability Engineer III',
    location: 'Hyderabad, Telangana, India',
    salary: '₹28 - ₹36 LPA',
    appliedAt: '2026-10-06',
    status: 'On Hold',
    endDate: '2026-10-24',
    vacancies: '4 Openings',
    source: 'LinkedIn',
    jobUrl: 'https://jobs.deloitte.com/job/hyderabad/applied-ai-sre-iii',
    summary: 'Applied AI and cloud reliability engineering across multi-cloud enterprise deployments.\nFocus on automated observability, incident response heuristics, and LLM agent infrastructure.',
    skills: ['Python', 'Kubernetes', 'Applied AI', 'GCP', 'Terraform'],
    notes: 'Initial conversation with recruiter completed. Position placed on hold until Q4 budget approval.',
    timeline: [
      { id: 't18', type: 'Applied', date: '2026-10-06', status: 'Applied' },
      { id: 't19', type: 'Recruiter Chat', date: '2026-10-06', status: 'On Hold' },
    ],
    createdAt: '2026-10-06T10:00:00.000Z',
    updatedAt: '2026-10-06T14:00:00.000Z',
  },
];
